exports.categories = [
  { name: "White appliances" },
  { name: "Refrigerators" },
  { name: "Washing machines" },
  { name: "Dishwasher machines" },
  { name: "Microwaves" },
  { name: "Electric grill machines" },
  { name: "Electric furnaces" },
  { name: "Electric ovens" },
  { name: "Blenders" },
  { name: "Mixers" },
  { name: "Electric Coffee Machines" },
  { name: "Toasters" },
  { name: "Food Processors" },
  { name: "Juicers" },
  { name: "Rice Cookers" },
  { name: "Pressure Cookers" },
  { name: "Slow Cookers" },
  { name: "Air Fryers" },
  { name: "Deep Fryers" },
  { name: "Electric Kettles" },
  { name: "Hand Blenders" },
  { name: "Hand Mixers" },
  { name: "Stand Mixers" },
  { name: "Bread Makers" },
  { name: "Waffle Makers" },
  { name: "Panini Presses" },
  { name: "Griddles" },
  { name: "Electric Skillets" },
  { name: "Electric Can Openers" },
  { name: "Electric Knives" },
  { name: "Food Dehydrators" },
  { name: "Ice Cream Makers" },
  { name: "Yogurt Makers" },
  { name: "Sous Vide Machines" },
  { name: "Vacuum Sealers" },
  { name: "Water Dispensers" },
  { name: "Humidifiers" },
  { name: "Air Purifiers" },
  { name: "Fans" },
  { name: "Heaters" },
  { name: "Portable Air Conditioners" },
  { name: "Window Air Conditioners" },
  { name: "Central Air Conditioning Systems" },
  { name: "Space Heaters" },
  { name: "Electric Fireplaces" },
  { name: "Garbage Disposals" },
];
