exports.categoryNames = [
  { name: "Refrigerators" },
  { name: "washing machines" },
  { name: "dishwasher machines" },
  { name: "microwaves" },
  { name: "electric grill machines" },
  { name: "electric furnaces " },
  { name: "electric ovens" },
  { name: "blenders" },
  { name: "mixers" },
  { name: "Electric Coffee Machines" },
  { name: "Drying Machines" },
  { name: "Irons" },
  { name: "Toasters" },
  { name: "Juicers " },
  { name: "Vacuum Cleaners" },
  { name: "Wet & dry Vacuum Cleaners" },
  { name: "water heaters" },
  { name: "Dough Mixer Machines " },
  { name: "humidifiers" },
  { name: "TVs" },
  { name: "Music Instruments" },
  { name: "Cameras" },
  { name: "Phones" },
  { name: "Tablets" },
  { name: "Smart Watches" },
  { name: "Headphones" },
  { name: "Monitors" },
  { name: "Motherboards" },
  { name: "Routers" },
  { name: "Wifi Extenders" },
  { name: "Printers" },
  { name: "Scanners" }
];
